"""Small shared core for notebook-first research platform modules."""

from .data_utils import as_df, first_available, normalize_name, normalize_ticker, resolve_alias
from .data_platform import (
    build_dataset_inventory,
    dataset_status,
    discover_financial_database_root,
    incremental_merge,
    load_catalog_tables,
    provider_fallback_plan,
    publish_artifacts_to_financial_db,
    read_dataset,
    read_dataset_drive_first,
    refresh_europe_stoxx_prices_incremental,
    resolve_data_platform_roots,
    resolve_dataset_path,
    should_refresh,
    summarize_inventory,
    write_data_platform_status,
    write_dataset_incremental,
)
from .api_management import (
    ApiControlRoots,
    accepted_api_env_vars,
    api_control_status,
    apply_env_text_to_session,
    build_env_template,
    build_credential_status,
    credential_master_sections,
    discover_api_credentials_root,
    load_api_folder_inventory,
    mask_secret,
    parse_env_text,
    resolve_api_control_roots,
    write_api_control_status,
)
from .batch_download import (
    EXPORT_FORMATS,
    create_batch_download,
    enrich_inventory_for_export,
    estimate_batch_size,
    infer_provider,
)
from .data_bridge import DataBridge
from .data_center_catalog import build_target_catalog, summarize_target_catalog
from .api_orchestrator import APIOrchestrator, ProviderSpec, RateLimiter
from .batch_downloader import BatchDownloader
from .cache_manager import DataCache, stable_cache_key
from .loaders.ecb_client import EcbClient, ECB_SERIES_PRESETS
from .loaders.bditalia_client import BancaDItaliaClient, BDITALIA_SERIES_PRESETS
from .macro_features import (
    add_standard_transformations,
    align_macro_frames,
    build_credit_risk_macro_dataset,
    build_inflation_nowcasting_dataset,
    save_macro_feature_panel,
    series_to_wide,
)
from .loaders.market_universe import MarketUniverseBuilder
from .loaders.ohlcv_client import OhlcvClient, normalize_ohlcv_frame, parse_yfinance_bulk
from .ohlcv_ingest import OhlcvIngestJob, summarize_ohlcv_manifest
from .ohlcv_store import OhlcvDatabase, default_database_url
from .research_database import (
    DEFAULT_SYMBOLS,
    SCHEMA_VERSION,
    ResearchDatabase,
    build_data_catalog_entries,
    build_strategy_registry,
    build_synthetic_research_dataset,
    default_research_database_path,
    populate_research_database,
)
from .llm_lab import (
    PROMPT_TEMPLATES,
    ProviderConfig,
    PromptTemplate,
    available_templates,
    build_context_from_database,
    provider_registry,
    provider_registry_frame,
    render_prompt,
    save_prompt_packet,
)
from .storage_policy import StorageRoots, export_storage_env, resolve_project_root, resolve_storage_roots
from .aqr_factors import (
    AqrDataset,
    AqrFactorProvider,
    discover_aqr_dataset_pages,
    discover_aqr_datasets,
    get_all_factors_panel,
    get_aqr_factor_panel,
    parse_aqr_excel,
    refresh_aqr_factor_library,
)
from .banking_data import (
    DEFAULT_BANK_IR_PAGES,
    FUNDAMENTALS_SCHEMA,
    ITALIAN_LISTED_BANK_TICKERS,
    build_banks_universe,
    build_ecb_bsi_macro_panel,
    build_market_panel,
    build_yfinance_bank_panel,
    calculate_bank_ratios,
    discover_bank_report_links,
    download_ecb_supervised_entities_pdf,
    ecb_get_series,
    fetch_bancaditalia_macro_regulatory,
    fetch_wikipedia_italian_banks,
    load_bancaditalia_bds_file,
    load_external_fundamentals,
    normalize_bank_name,
    parse_bank_annual_report,
    parse_ecb_supervised_entities_pdf,
    run_banks_data_pipeline,
)
from .export_utils import output_root_from_namespace, safe_write_csv, safe_write_json
from .html_utils import table_html

__all__ = [
    "as_df",
    "first_available",
    "normalize_name",
    "normalize_ticker",
    "resolve_alias",
    "build_dataset_inventory",
    "dataset_status",
    "discover_financial_database_root",
    "incremental_merge",
    "load_catalog_tables",
    "provider_fallback_plan",
    "publish_artifacts_to_financial_db",
    "read_dataset",
    "read_dataset_drive_first",
    "refresh_europe_stoxx_prices_incremental",
    "resolve_data_platform_roots",
    "resolve_dataset_path",
    "should_refresh",
    "summarize_inventory",
    "write_data_platform_status",
    "write_dataset_incremental",
    "ApiControlRoots",
    "accepted_api_env_vars",
    "api_control_status",
    "apply_env_text_to_session",
    "build_env_template",
    "build_credential_status",
    "credential_master_sections",
    "discover_api_credentials_root",
    "load_api_folder_inventory",
    "mask_secret",
    "parse_env_text",
    "resolve_api_control_roots",
    "write_api_control_status",
    "EXPORT_FORMATS",
    "create_batch_download",
    "enrich_inventory_for_export",
    "estimate_batch_size",
    "infer_provider",
    "DataBridge",
    "build_target_catalog",
    "summarize_target_catalog",
    "APIOrchestrator",
    "ProviderSpec",
    "RateLimiter",
    "BatchDownloader",
    "DataCache",
    "stable_cache_key",
    "EcbClient",
    "ECB_SERIES_PRESETS",
    "BancaDItaliaClient",
    "BDITALIA_SERIES_PRESETS",
    "add_standard_transformations",
    "align_macro_frames",
    "build_credit_risk_macro_dataset",
    "build_inflation_nowcasting_dataset",
    "save_macro_feature_panel",
    "series_to_wide",
    "MarketUniverseBuilder",
    "OhlcvClient",
    "normalize_ohlcv_frame",
    "parse_yfinance_bulk",
    "OhlcvIngestJob",
    "summarize_ohlcv_manifest",
    "OhlcvDatabase",
    "default_database_url",
    "DEFAULT_SYMBOLS",
    "SCHEMA_VERSION",
    "ResearchDatabase",
    "build_data_catalog_entries",
    "build_strategy_registry",
    "build_synthetic_research_dataset",
    "default_research_database_path",
    "populate_research_database",
    "PROMPT_TEMPLATES",
    "ProviderConfig",
    "PromptTemplate",
    "available_templates",
    "build_context_from_database",
    "provider_registry",
    "provider_registry_frame",
    "render_prompt",
    "save_prompt_packet",
    "StorageRoots",
    "export_storage_env",
    "resolve_project_root",
    "resolve_storage_roots",
    "AqrDataset",
    "AqrFactorProvider",
    "discover_aqr_dataset_pages",
    "discover_aqr_datasets",
    "get_all_factors_panel",
    "get_aqr_factor_panel",
    "parse_aqr_excel",
    "refresh_aqr_factor_library",
    "DEFAULT_BANK_IR_PAGES",
    "FUNDAMENTALS_SCHEMA",
    "ITALIAN_LISTED_BANK_TICKERS",
    "build_banks_universe",
    "build_ecb_bsi_macro_panel",
    "build_market_panel",
    "build_yfinance_bank_panel",
    "calculate_bank_ratios",
    "discover_bank_report_links",
    "download_ecb_supervised_entities_pdf",
    "ecb_get_series",
    "fetch_bancaditalia_macro_regulatory",
    "fetch_wikipedia_italian_banks",
    "load_bancaditalia_bds_file",
    "load_external_fundamentals",
    "normalize_bank_name",
    "parse_bank_annual_report",
    "parse_ecb_supervised_entities_pdf",
    "run_banks_data_pipeline",
    "output_root_from_namespace",
    "safe_write_csv",
    "safe_write_json",
    "table_html",
]
