"""Small shared core for notebook-first research platform modules."""

from .data_utils import as_df, first_available, normalize_name, normalize_ticker, resolve_alias
from .data_platform import (
    OhlcvParquetRoot,
    build_dataset_inventory,
    dataset_status,
    discover_financial_database_root,
    get_ohlcv_daily_search_roots,
    get_ohlcv_parquet_root,
    get_ohlcv_parquet_root_info,
    incremental_merge,
    is_cloud_backed_path,
    load_catalog_tables,
    provider_fallback_plan,
    publish_artifacts_to_financial_db,
    read_dataset,
    read_dataset_drive_first,
    recent_run_logs,
    refresh_europe_stoxx_prices_incremental,
    resolve_data_platform_roots,
    resolve_dataset_path,
    should_refresh,
    shared_database_contract,
    summarize_inventory,
    write_data_platform_status,
    write_dataset_incremental,
)
from .api_management import (
    ApiControlRoots,
    accepted_api_env_vars,
    api_control_status,
    apply_env_text_to_session,
    build_env_template,
    build_credential_status,
    credential_master_sections,
    discover_api_credentials_root,
    load_api_folder_inventory,
    mask_secret,
    parse_env_text,
    resolve_api_control_roots,
    write_api_control_status,
)
from .batch_download import (
    EXPORT_FORMATS,
    create_batch_download,
    enrich_inventory_for_export,
    estimate_batch_size,
    infer_provider,
)
from .data_bridge import DataBridge
from .data_center_catalog import build_target_catalog, summarize_target_catalog
from .api_orchestrator import APIOrchestrator, ApiOrchestrator, ProviderSpec, RateLimiter, get_fundamentals_waterfall
from .alpha101 import Alpha101Suite
from .batch_downloader import BatchDownloader
from .cache_manager import DataCache, stable_cache_key
from .loaders.ecb_client import EcbClient, ECB_SERIES_PRESETS
from .loaders.bditalia_client import BancaDItaliaClient, BDITALIA_SERIES_PRESETS
from .macro_features import (
    add_standard_transformations,
    align_macro_frames,
    build_credit_risk_macro_dataset,
    build_inflation_nowcasting_dataset,
    save_macro_feature_panel,
    series_to_wide,
)
from .loaders.market_universe import MarketUniverseBuilder
from .loaders.ohlcv_client import OhlcvClient, classify_history_window, classify_provider_error, normalize_ohlcv_frame, parse_yfinance_bulk
from .ohlcv_ingest import OhlcvIngestJob, summarize_ohlcv_manifest, validate_provider_symbol
from .ohlcv_store import OhlcvDatabase, default_database_url
from .storage_policy import StorageRoots, export_storage_env, resolve_project_root, resolve_storage_roots
from .aqr_factors import (
    AqrDataset,
    AqrFactorProvider,
    construct_it_local_factors,
    discover_aqr_dataset_pages,
    discover_aqr_datasets,
    download_ff_factors,
    get_all_factors_panel,
    get_aqr_factor_panel,
    load_all_regional_factors,
    parse_aqr_excel,
    parse_aqr_excel_robust,
    refresh_aqr_factor_library,
)
from .italy_local_factors import (
    ITALY_LOCAL_UNIVERSE,
    build_italy_factor_panel,
    fetch_ecb_sovereign_spread,
    fetch_eurostat_macro,
)
from .banking_data import (
    DEFAULT_BANK_IR_PAGES,
    FUNDAMENTALS_SCHEMA,
    ITALIAN_LISTED_BANK_TICKERS,
    build_banks_universe,
    build_ecb_bsi_macro_panel,
    build_market_panel,
    build_yfinance_bank_panel,
    calculate_bank_ratios,
    curated_listed_bank_universe,
    discover_bank_report_links,
    download_ecb_supervised_entities_pdf,
    ecb_get_series,
    fetch_bancaditalia_macro_regulatory,
    fetch_wikipedia_italian_banks,
    load_bancaditalia_bds_file,
    load_external_fundamentals,
    normalize_bank_name,
    parse_bank_annual_report,
    parse_ecb_supervised_entities_pdf,
    run_banks_data_pipeline,
)
from .export_utils import output_root_from_namespace, safe_write_csv, safe_write_json
from .html_utils import table_html
from .data_completion import (
    CompletionConfig,
    ResearchDataBootstrapper,
    bootstrap_banking_universe,
    bootstrap_equity_fundamentals,
    bootstrap_equity_prices,
    bootstrap_macro_fx_series,
    bootstrap_smart_money_data,
    build_factor_universe_panel,
    data_source_map,
    run_full_data_completion,
    validate_completion_coverage,
)
from .data_health import (
    StageHealth,
    TickerDataStatus,
    get_data_health_summary,
    get_data_status_for_tickers,
    get_stage_health_for_universes,
    list_ohlcv_failures,
    list_ohlcv_provider_failures,
    load_run_events,
    restart_equity_prices,
    restart_equity_prices_failed_only,
)
from .data_explorer import (
    find_ohlcv_parquet,
    get_single_ticker_snapshot,
    get_ticker_context,
    list_available_tickers,
    load_company_rows_for_ticker,
    load_data_explorer_preview,
    load_factor_rows_for_ticker,
    load_ml_signal_rows_for_ticker,
    load_portfolio_rows_for_ticker,
    load_ticker_ohlcv,
)
from .llm_client import LlmResponse, OllamaClient
from .llm_prompts import PROMPT_REGISTRY
from .llm_advisors import advise_forecast_horizon, advise_model_configuration, audit_model_governance, explain_stock_picks, suggest_screener_config
from .macro_market import MACRO_ASSETS, MacroAsset, compile_macro_asset_database, load_macro_market_artifacts, macro_asset_catalog
from .macro_context import add_macro_context_features, build_macro_context_panel, load_macro_close_panel, load_macro_context_panel
from .multi_asset_universe import (
    compile_multi_asset_universe_manifest,
    ingest_multi_asset_universe,
    load_multi_asset_universe_manifest,
    multi_asset_universe_catalog,
    summarize_multi_asset_universe,
)
from .factor_benchmarks import (
    DEFAULT_FACTORS,
    compute_factor_benchmark_summary,
    discover_factor_panel_path,
    load_factor_benchmark_summary,
    write_factor_benchmark_artifacts,
)
from .factor_portfolio_baselines import (
    compute_factor_portfolio_baselines,
    load_factor_portfolio_baselines,
    write_factor_portfolio_baselines,
)
from .model_monitoring import build_model_monitoring_artifacts, discover_prediction_path, load_model_monitoring_artifacts
from .smart_money import (
    compile_smart_money_asset_catalog,
    compile_smart_money_source_manifest,
    fetch_cot_data,
    fetch_etf_flows_proxy,
    fetch_options_put_call_ratio,
    get_pcr_cboe_bulk,
    get_pcr_fmp,
    get_pcr_polygon,
    load_smart_money_source_manifest,
    normalize_cot_data,
    refresh_cftc_cot_snapshot,
    smart_money_source_catalog,
    summarize_smart_money_sources,
)
from .equity_feature_engineering import compute_alpha_factors, compute_investment_factors, compute_sentiment_alternative_features
from .regime_detection import build_market_regime_history, detect_market_regime, load_market_regime_history
from .sentiment_analysis import collect_ticker_sentiment, fetch_reddit_mentions, fetch_stocktwits_messages, fetch_x_recent_mentions, score_sentiment_frame, score_text
from .run_lock import LockInfo, acquire_stage_lock, is_stage_locked, read_stage_lock, release_stage_lock, stage_lock_path
from .feature_metadata import FEATURE_METADATA, FeatureMetadata, category_for_feature, metadata_for_feature, metadata_frame, metadata_help
from .metrics_metadata import METRICS_METADATA, MetricMetadata, metadata_for_metric, metric_help, metrics_metadata_frame
from .time_series_forecasting import (
    TimeSeriesForecastConfig,
    TimeSeriesForecastResult,
    available_time_series_assets,
    fit_time_series_forecasts,
    load_equity_series,
    load_macro_series,
    load_time_series_forecast_artifacts,
    make_time_series_features,
    prepare_time_series_frame,
    run_time_series_forecast,
    summarize_time_series_forecast_context,
    write_time_series_forecast_artifacts,
)
from .market_statistics import (
    compute_correlation_matrix,
    compute_ticker_market_statistics,
    load_price_return_matrix,
    summarize_correlation_matrix,
)
from .portfolio_analytics import (
    compute_brinson_attribution,
    compute_efficient_frontier,
    compute_max_sharpe_weights,
    compute_min_variance_weights,
    compute_portfolio_performance_metrics,
    compute_risk_parity_weights,
)
from .valuation_analytics import (
    compute_asset_based_valuation,
    compute_comps_valuation,
    compute_dcf_valuation,
    compute_ddm_valuation,
    compute_eva_residual_income,
    compute_market_multiples,
    compute_wacc,
    fair_value_summary,
)
from .equity_feature_engineering import (
    add_advanced_equity_features,
    compute_advanced_fundamental_features,
    compute_advanced_technical_features,
    compute_piotroski_f_score,
)

__all__ = [
    "as_df",
    "first_available",
    "normalize_name",
    "normalize_ticker",
    "resolve_alias",
    "build_dataset_inventory",
    "dataset_status",
    "discover_financial_database_root",
    "get_ohlcv_daily_search_roots",
    "get_ohlcv_parquet_root",
    "get_ohlcv_parquet_root_info",
    "incremental_merge",
    "is_cloud_backed_path",
    "load_catalog_tables",
    "OhlcvParquetRoot",
    "provider_fallback_plan",
    "publish_artifacts_to_financial_db",
    "read_dataset",
    "read_dataset_drive_first",
    "recent_run_logs",
    "refresh_europe_stoxx_prices_incremental",
    "resolve_data_platform_roots",
    "resolve_dataset_path",
    "should_refresh",
    "shared_database_contract",
    "summarize_inventory",
    "write_data_platform_status",
    "write_dataset_incremental",
    "ApiControlRoots",
    "accepted_api_env_vars",
    "api_control_status",
    "apply_env_text_to_session",
    "build_env_template",
    "build_credential_status",
    "credential_master_sections",
    "discover_api_credentials_root",
    "load_api_folder_inventory",
    "mask_secret",
    "parse_env_text",
    "resolve_api_control_roots",
    "write_api_control_status",
    "EXPORT_FORMATS",
    "create_batch_download",
    "enrich_inventory_for_export",
    "estimate_batch_size",
    "infer_provider",
    "DataBridge",
    "build_target_catalog",
    "summarize_target_catalog",
    "APIOrchestrator",
    "ApiOrchestrator",
    "Alpha101Suite",
    "get_fundamentals_waterfall",
    "ProviderSpec",
    "RateLimiter",
    "BatchDownloader",
    "DataCache",
    "stable_cache_key",
    "EcbClient",
    "ECB_SERIES_PRESETS",
    "BancaDItaliaClient",
    "BDITALIA_SERIES_PRESETS",
    "add_standard_transformations",
    "align_macro_frames",
    "build_credit_risk_macro_dataset",
    "build_inflation_nowcasting_dataset",
    "save_macro_feature_panel",
    "series_to_wide",
    "MarketUniverseBuilder",
    "OhlcvClient",
    "classify_history_window",
    "classify_provider_error",
    "normalize_ohlcv_frame",
    "parse_yfinance_bulk",
    "OhlcvIngestJob",
    "summarize_ohlcv_manifest",
    "validate_provider_symbol",
    "OhlcvDatabase",
    "default_database_url",
    "StorageRoots",
    "export_storage_env",
    "resolve_project_root",
    "resolve_storage_roots",
    "AqrDataset",
    "AqrFactorProvider",
    "discover_aqr_dataset_pages",
    "discover_aqr_datasets",
    "get_all_factors_panel",
    "get_aqr_factor_panel",
    "load_all_regional_factors",
    "parse_aqr_excel",
    "parse_aqr_excel_robust",
    "refresh_aqr_factor_library",
    "download_ff_factors",
    "construct_it_local_factors",
    "ITALY_LOCAL_UNIVERSE",
    "build_italy_factor_panel",
    "fetch_ecb_sovereign_spread",
    "fetch_eurostat_macro",
    "DEFAULT_BANK_IR_PAGES",
    "FUNDAMENTALS_SCHEMA",
    "ITALIAN_LISTED_BANK_TICKERS",
    "build_banks_universe",
    "build_ecb_bsi_macro_panel",
    "build_market_panel",
    "build_yfinance_bank_panel",
    "calculate_bank_ratios",
    "curated_listed_bank_universe",
    "discover_bank_report_links",
    "download_ecb_supervised_entities_pdf",
    "ecb_get_series",
    "fetch_bancaditalia_macro_regulatory",
    "fetch_wikipedia_italian_banks",
    "load_bancaditalia_bds_file",
    "load_external_fundamentals",
    "normalize_bank_name",
    "parse_bank_annual_report",
    "parse_ecb_supervised_entities_pdf",
    "run_banks_data_pipeline",
    "output_root_from_namespace",
    "safe_write_csv",
    "safe_write_json",
    "table_html",
    "CompletionConfig",
    "ResearchDataBootstrapper",
    "bootstrap_banking_universe",
    "bootstrap_equity_fundamentals",
    "bootstrap_equity_prices",
    "bootstrap_macro_fx_series",
    "bootstrap_smart_money_data",
    "build_factor_universe_panel",
    "data_source_map",
    "run_full_data_completion",
    "validate_completion_coverage",
    "get_data_health_summary",
    "StageHealth",
    "TickerDataStatus",
    "get_data_status_for_tickers",
    "get_stage_health_for_universes",
    "list_ohlcv_failures",
    "list_ohlcv_provider_failures",
    "load_run_events",
    "restart_equity_prices",
    "restart_equity_prices_failed_only",
    "find_ohlcv_parquet",
    "get_single_ticker_snapshot",
    "get_ticker_context",
    "list_available_tickers",
    "load_company_rows_for_ticker",
    "load_data_explorer_preview",
    "load_factor_rows_for_ticker",
    "load_ml_signal_rows_for_ticker",
    "load_portfolio_rows_for_ticker",
    "load_ticker_ohlcv",
    "LlmResponse",
    "OllamaClient",
    "PROMPT_REGISTRY",
    "advise_forecast_horizon",
    "advise_model_configuration",
    "audit_model_governance",
    "explain_stock_picks",
    "suggest_screener_config",
    "MACRO_ASSETS",
    "MacroAsset",
    "compile_macro_asset_database",
    "load_macro_market_artifacts",
    "macro_asset_catalog",
    "add_macro_context_features",
    "build_macro_context_panel",
    "load_macro_close_panel",
    "load_macro_context_panel",
    "compile_multi_asset_universe_manifest",
    "load_multi_asset_universe_manifest",
    "summarize_multi_asset_universe",
    "DEFAULT_FACTORS",
    "compute_factor_benchmark_summary",
    "discover_factor_panel_path",
    "load_factor_benchmark_summary",
    "write_factor_benchmark_artifacts",
    "compile_smart_money_source_manifest",
    "fetch_cot_data",
    "fetch_etf_flows_proxy",
    "fetch_options_put_call_ratio",
    "get_pcr_cboe_bulk",
    "get_pcr_fmp",
    "get_pcr_polygon",
    "load_smart_money_source_manifest",
    "normalize_cot_data",
    "refresh_cftc_cot_snapshot",
    "smart_money_source_catalog",
    "summarize_smart_money_sources",
    "build_market_regime_history",
    "detect_market_regime",
    "load_market_regime_history",
    "collect_ticker_sentiment",
    "fetch_reddit_mentions",
    "fetch_stocktwits_messages",
    "fetch_x_recent_mentions",
    "score_sentiment_frame",
    "score_text",
    "LockInfo",
    "acquire_stage_lock",
    "is_stage_locked",
    "read_stage_lock",
    "release_stage_lock",
    "stage_lock_path",
    "FEATURE_METADATA",
    "FeatureMetadata",
    "category_for_feature",
    "metadata_for_feature",
    "metadata_frame",
    "metadata_help",
    "METRICS_METADATA",
    "MetricMetadata",
    "metadata_for_metric",
    "metric_help",
    "metrics_metadata_frame",
    "TimeSeriesForecastConfig",
    "TimeSeriesForecastResult",
    "available_time_series_assets",
    "fit_time_series_forecasts",
    "load_equity_series",
    "load_macro_series",
    "load_time_series_forecast_artifacts",
    "make_time_series_features",
    "prepare_time_series_frame",
    "run_time_series_forecast",
    "summarize_time_series_forecast_context",
    "write_time_series_forecast_artifacts",
    "compute_correlation_matrix",
    "compute_ticker_market_statistics",
    "load_price_return_matrix",
    "summarize_correlation_matrix",
    "compute_brinson_attribution",
    "compute_efficient_frontier",
    "compute_max_sharpe_weights",
    "compute_min_variance_weights",
    "compute_portfolio_performance_metrics",
    "compute_risk_parity_weights",
    "compute_asset_based_valuation",
    "compute_comps_valuation",
    "compute_dcf_valuation",
    "compute_ddm_valuation",
    "compute_eva_residual_income",
    "compute_market_multiples",
    "compute_wacc",
    "fair_value_summary",
    "add_advanced_equity_features",
    "compute_advanced_fundamental_features",
    "compute_advanced_technical_features",
    "compute_alpha_factors",
    "compute_investment_factors",
    "compute_piotroski_f_score",
    "compute_sentiment_alternative_features",
]
