"""Small shared core for notebook-first research platform modules."""

from .data_utils import as_df, first_available, normalize_name, normalize_ticker, resolve_alias
from .data_platform import (
    OhlcvParquetRoot,
    build_dataset_inventory,
    dataset_status,
    discover_financial_database_root,
    get_ohlcv_daily_search_roots,
    get_ohlcv_parquet_root,
    get_ohlcv_parquet_root_info,
    incremental_merge,
    is_cloud_backed_path,
    load_catalog_tables,
    provider_fallback_plan,
    publish_artifacts_to_financial_db,
    read_dataset,
    read_dataset_drive_first,
    recent_run_logs,
    refresh_europe_stoxx_prices_incremental,
    resolve_data_platform_roots,
    resolve_dataset_path,
    should_refresh,
    shared_database_contract,
    summarize_inventory,
    write_data_platform_status,
    write_dataset_incremental,
)
from .api_management import (
    ApiControlRoots,
    accepted_api_env_vars,
    api_control_status,
    apply_env_text_to_session,
    build_env_template,
    build_credential_status,
    credential_master_sections,
    discover_api_credentials_root,
    load_api_folder_inventory,
    mask_secret,
    parse_env_text,
    resolve_api_control_roots,
    write_api_control_status,
)
from .batch_download import (
    EXPORT_FORMATS,
    create_batch_download,
    enrich_inventory_for_export,
    estimate_batch_size,
    infer_provider,
)
from .data_bridge import DataBridge
from .data_center_catalog import build_target_catalog, summarize_target_catalog
from .api_orchestrator import APIOrchestrator, ProviderSpec, RateLimiter
from .batch_downloader import BatchDownloader
from .cache_manager import DataCache, stable_cache_key
from .loaders.ecb_client import EcbClient, ECB_SERIES_PRESETS
from .loaders.bditalia_client import BancaDItaliaClient, BDITALIA_SERIES_PRESETS
from .macro_features import (
    add_standard_transformations,
    align_macro_frames,
    build_credit_risk_macro_dataset,
    build_inflation_nowcasting_dataset,
    save_macro_feature_panel,
    series_to_wide,
)
from .loaders.market_universe import MarketUniverseBuilder
from .loaders.ohlcv_client import OhlcvClient, classify_history_window, classify_provider_error, normalize_ohlcv_frame, parse_yfinance_bulk
from .ohlcv_ingest import OhlcvIngestJob, summarize_ohlcv_manifest, validate_provider_symbol
from .ohlcv_store import OhlcvDatabase, default_database_url
from .storage_policy import StorageRoots, export_storage_env, resolve_project_root, resolve_storage_roots
from .aqr_factors import (
    AqrDataset,
    AqrFactorProvider,
    discover_aqr_dataset_pages,
    discover_aqr_datasets,
    get_all_factors_panel,
    get_aqr_factor_panel,
    parse_aqr_excel,
    refresh_aqr_factor_library,
)
from .banking_data import (
    DEFAULT_BANK_IR_PAGES,
    FUNDAMENTALS_SCHEMA,
    ITALIAN_LISTED_BANK_TICKERS,
    build_banks_universe,
    build_ecb_bsi_macro_panel,
    build_market_panel,
    build_yfinance_bank_panel,
    calculate_bank_ratios,
    discover_bank_report_links,
    download_ecb_supervised_entities_pdf,
    ecb_get_series,
    fetch_bancaditalia_macro_regulatory,
    fetch_wikipedia_italian_banks,
    load_bancaditalia_bds_file,
    load_external_fundamentals,
    normalize_bank_name,
    parse_bank_annual_report,
    parse_ecb_supervised_entities_pdf,
    run_banks_data_pipeline,
)
from .export_utils import output_root_from_namespace, safe_write_csv, safe_write_json
from .html_utils import table_html
from .data_completion import (
    CompletionConfig,
    ResearchDataBootstrapper,
    bootstrap_banking_universe,
    bootstrap_equity_fundamentals,
    bootstrap_equity_prices,
    bootstrap_macro_fx_series,
    bootstrap_smart_money_data,
    build_factor_universe_panel,
    data_source_map,
    run_full_data_completion,
    validate_completion_coverage,
)
from .data_health import (
    StageHealth,
    TickerDataStatus,
    get_data_health_summary,
    get_data_status_for_tickers,
    get_stage_health_for_universes,
    list_ohlcv_failures,
    list_ohlcv_provider_failures,
    load_run_events,
    restart_equity_prices,
    restart_equity_prices_failed_only,
)
from .data_explorer import (
    find_ohlcv_parquet,
    get_single_ticker_snapshot,
    get_ticker_context,
    list_available_tickers,
    load_company_rows_for_ticker,
    load_data_explorer_preview,
    load_factor_rows_for_ticker,
    load_ml_signal_rows_for_ticker,
    load_portfolio_rows_for_ticker,
    load_ticker_ohlcv,
)
from .llm_client import LlmResponse, OllamaClient
from .llm_prompts import PROMPT_REGISTRY
from .llm_advisors import advise_forecast_horizon, advise_model_configuration, audit_model_governance, explain_stock_picks, suggest_screener_config
from .run_lock import LockInfo, acquire_stage_lock, is_stage_locked, read_stage_lock, release_stage_lock, stage_lock_path

__all__ = [
    "as_df",
    "first_available",
    "normalize_name",
    "normalize_ticker",
    "resolve_alias",
    "build_dataset_inventory",
    "dataset_status",
    "discover_financial_database_root",
    "get_ohlcv_daily_search_roots",
    "get_ohlcv_parquet_root",
    "get_ohlcv_parquet_root_info",
    "incremental_merge",
    "is_cloud_backed_path",
    "load_catalog_tables",
    "OhlcvParquetRoot",
    "provider_fallback_plan",
    "publish_artifacts_to_financial_db",
    "read_dataset",
    "read_dataset_drive_first",
    "recent_run_logs",
    "refresh_europe_stoxx_prices_incremental",
    "resolve_data_platform_roots",
    "resolve_dataset_path",
    "should_refresh",
    "shared_database_contract",
    "summarize_inventory",
    "write_data_platform_status",
    "write_dataset_incremental",
    "ApiControlRoots",
    "accepted_api_env_vars",
    "api_control_status",
    "apply_env_text_to_session",
    "build_env_template",
    "build_credential_status",
    "credential_master_sections",
    "discover_api_credentials_root",
    "load_api_folder_inventory",
    "mask_secret",
    "parse_env_text",
    "resolve_api_control_roots",
    "write_api_control_status",
    "EXPORT_FORMATS",
    "create_batch_download",
    "enrich_inventory_for_export",
    "estimate_batch_size",
    "infer_provider",
    "DataBridge",
    "build_target_catalog",
    "summarize_target_catalog",
    "APIOrchestrator",
    "ProviderSpec",
    "RateLimiter",
    "BatchDownloader",
    "DataCache",
    "stable_cache_key",
    "EcbClient",
    "ECB_SERIES_PRESETS",
    "BancaDItaliaClient",
    "BDITALIA_SERIES_PRESETS",
    "add_standard_transformations",
    "align_macro_frames",
    "build_credit_risk_macro_dataset",
    "build_inflation_nowcasting_dataset",
    "save_macro_feature_panel",
    "series_to_wide",
    "MarketUniverseBuilder",
    "OhlcvClient",
    "classify_history_window",
    "classify_provider_error",
    "normalize_ohlcv_frame",
    "parse_yfinance_bulk",
    "OhlcvIngestJob",
    "summarize_ohlcv_manifest",
    "validate_provider_symbol",
    "OhlcvDatabase",
    "default_database_url",
    "StorageRoots",
    "export_storage_env",
    "resolve_project_root",
    "resolve_storage_roots",
    "AqrDataset",
    "AqrFactorProvider",
    "discover_aqr_dataset_pages",
    "discover_aqr_datasets",
    "get_all_factors_panel",
    "get_aqr_factor_panel",
    "parse_aqr_excel",
    "refresh_aqr_factor_library",
    "DEFAULT_BANK_IR_PAGES",
    "FUNDAMENTALS_SCHEMA",
    "ITALIAN_LISTED_BANK_TICKERS",
    "build_banks_universe",
    "build_ecb_bsi_macro_panel",
    "build_market_panel",
    "build_yfinance_bank_panel",
    "calculate_bank_ratios",
    "discover_bank_report_links",
    "download_ecb_supervised_entities_pdf",
    "ecb_get_series",
    "fetch_bancaditalia_macro_regulatory",
    "fetch_wikipedia_italian_banks",
    "load_bancaditalia_bds_file",
    "load_external_fundamentals",
    "normalize_bank_name",
    "parse_bank_annual_report",
    "parse_ecb_supervised_entities_pdf",
    "run_banks_data_pipeline",
    "output_root_from_namespace",
    "safe_write_csv",
    "safe_write_json",
    "table_html",
    "CompletionConfig",
    "ResearchDataBootstrapper",
    "bootstrap_banking_universe",
    "bootstrap_equity_fundamentals",
    "bootstrap_equity_prices",
    "bootstrap_macro_fx_series",
    "bootstrap_smart_money_data",
    "build_factor_universe_panel",
    "data_source_map",
    "run_full_data_completion",
    "validate_completion_coverage",
    "get_data_health_summary",
    "StageHealth",
    "TickerDataStatus",
    "get_data_status_for_tickers",
    "get_stage_health_for_universes",
    "list_ohlcv_failures",
    "list_ohlcv_provider_failures",
    "load_run_events",
    "restart_equity_prices",
    "restart_equity_prices_failed_only",
    "find_ohlcv_parquet",
    "get_single_ticker_snapshot",
    "get_ticker_context",
    "list_available_tickers",
    "load_company_rows_for_ticker",
    "load_data_explorer_preview",
    "load_factor_rows_for_ticker",
    "load_ml_signal_rows_for_ticker",
    "load_portfolio_rows_for_ticker",
    "load_ticker_ohlcv",
    "LlmResponse",
    "OllamaClient",
    "PROMPT_REGISTRY",
    "advise_forecast_horizon",
    "advise_model_configuration",
    "audit_model_governance",
    "explain_stock_picks",
    "suggest_screener_config",
    "LockInfo",
    "acquire_stage_lock",
    "is_stage_locked",
    "read_stage_lock",
    "release_stage_lock",
    "stage_lock_path",
]
