"""ml_stock_lab: reusable ML equity valuation, signals and diagnostics tools."""

from .datasets import (
    FundamentalDatasetBuilder,
    add_basic_features,
    build_company_selection_panel,
    build_company_selection_widget,
    company_source_paths,
    filter_company_selection_panel,
    load_financial_db_panel,
    load_panel_csv,
    make_forward_returns,
    normalize_panel,
    select_numeric_features,
)
from .evaluation import (
    ExperimentStatus,
    FactorAlphaEvaluator,
    PanelValidationResult,
    PerformanceMetrics,
    annualized_volatility,
    build_status_from_signals,
    max_drawdown,
    plot_cumulative_returns,
    quintile_risk_report,
    save_status_file,
    sharpe_ratio,
    should_run_experiment,
    turnover,
    validate_panel,
)
from .prediction import FundamentalPredictorRF, ExpectedReturnModel, describe_temporal_split, oos_r2, temporal_train_test_split
from .signals import (
    EnsembleMispricingSignal,
    MispricingSignal,
    assign_quantiles,
    compute_absolute_mispricing,
    compute_relative_mispricing,
    cross_sectional_zscore,
    make_quantile_portfolios,
    quintile_returns_wide,
    rank_scores,
    top_bottom,
)
from .tracking import build_experiment_summary, save_experiment_summary
from .valuation import (
    PeerImpliedGBRT,
    PeerImpliedLasso,
    PeerImpliedOLS,
    PeerImpliedRF,
    PeerImpliedValuator,
    PeerOLSValuator,
    RollingPeerValuator,
)

__all__ = [
    "EnsembleMispricingSignal",
    "ExperimentStatus",
    "ExpectedReturnModel",
    "FactorAlphaEvaluator",
    "FundamentalPredictorRF",
    "FundamentalDatasetBuilder",
    "MispricingSignal",
    "PanelValidationResult",
    "PeerImpliedGBRT",
    "PeerImpliedLasso",
    "PeerImpliedOLS",
    "PeerImpliedRF",
    "PeerImpliedValuator",
    "PeerOLSValuator",
    "PerformanceMetrics",
    "RollingPeerValuator",
    "add_basic_features",
    "annualized_volatility",
    "assign_quantiles",
    "build_company_selection_panel",
    "build_company_selection_widget",
    "build_experiment_summary",
    "build_status_from_signals",
    "company_source_paths",
    "compute_absolute_mispricing",
    "compute_relative_mispricing",
    "cross_sectional_zscore",
    "describe_temporal_split",
    "filter_company_selection_panel",
    "load_financial_db_panel",
    "load_panel_csv",
    "make_forward_returns",
    "make_quantile_portfolios",
    "max_drawdown",
    "normalize_panel",
    "oos_r2",
    "plot_cumulative_returns",
    "quintile_returns_wide",
    "quintile_risk_report",
    "rank_scores",
    "save_experiment_summary",
    "save_status_file",
    "select_numeric_features",
    "sharpe_ratio",
    "should_run_experiment",
    "temporal_train_test_split",
    "top_bottom",
    "turnover",
    "validate_panel",
]
