"""Strategy interface shared by Vibe-Trading and local backtests."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Mapping

import numpy as np
import pandas as pd


@dataclass(slots=True)
class StrategyContext:
    """Runtime context passed to strategy hooks."""

    date: pd.Timestamp
    universe: list[str]
    cash: float | None = None
    positions: Mapping[str, float] = field(default_factory=dict)
    metadata: Mapping[str, Any] = field(default_factory=dict)


class StrategyBase(ABC):
    """Base class for strategies generated by Vibe-Trading.

    Subclasses can either implement ``on_bar`` and inherit the default event
    loop, or override ``generate_signals`` for vectorized research code. Signal
    frames should include ``date``, ``ticker`` and either ``signal`` or
    ``target_weight``.
    """

    strategy_name = "strategy_base"

    def __init__(self, **params: Any) -> None:
        self.params = dict(params)
        self.name = str(self.params.get("name", self.strategy_name))

    def on_start(self, context: StrategyContext) -> None:
        """Hook called before backtest signal generation starts."""

    @abstractmethod
    def on_bar(
        self,
        context: StrategyContext,
        historical_data: pd.DataFrame,
        features: pd.DataFrame | None = None,
    ) -> Mapping[str, float] | pd.DataFrame:
        """Return desired signal or target weight values for the current bar."""

    def on_end(self, context: StrategyContext) -> None:
        """Hook called after backtest signal generation ends."""

    def generate_signals(
        self,
        current_state: Mapping[str, Any] | None,
        historical_data: pd.DataFrame,
        features: pd.DataFrame | None = None,
    ) -> pd.DataFrame:
        """Generate a full signal frame from bar-by-bar strategy hooks."""

        if historical_data.empty or "date" not in historical_data.columns:
            return pd.DataFrame(columns=["date", "ticker", "signal"])

        data = historical_data.copy()
        data["date"] = pd.to_datetime(data["date"], errors="coerce")
        universe = sorted(data.get("ticker", pd.Series(dtype=str)).dropna().astype(str).unique().tolist())
        dates = data["date"].dropna().sort_values().unique()
        frames: list[pd.DataFrame] = []

        if len(dates) == 0:
            return pd.DataFrame(columns=["date", "ticker", "signal"])

        start_context = StrategyContext(date=pd.Timestamp(dates[0]), universe=universe, metadata=dict(current_state or {}))
        self.on_start(start_context)

        for date_value in dates:
            date = pd.Timestamp(date_value)
            hist_slice = data[data["date"] <= date]
            feature_slice = _feature_slice(features, date)
            context = StrategyContext(date=date, universe=universe, metadata=dict(current_state or {}))
            result = self.on_bar(context, hist_slice, feature_slice)
            frames.append(_coerce_bar_result(result, date))

        end_context = StrategyContext(date=pd.Timestamp(dates[-1]), universe=universe, metadata=dict(current_state or {}))
        self.on_end(end_context)
        return validate_signal_frame(pd.concat(frames, ignore_index=True) if frames else pd.DataFrame())


class MovingAverageCrossOverStrategy(StrategyBase):
    """Simple moving-average crossover example.

    Parameters:
        fast_window: Number of bars for the fast moving average.
        slow_window: Number of bars for the slow moving average.
        price_col: Price column used for the signal calculation.
        long_only: If true, produce 1/0 signals; otherwise produce 1/-1.
    Formula:
        signal[t, i] = 1 when SMA_fast(price_i) > SMA_slow(price_i), else
        0 for long-only or -1 for long-short mode.
    """

    strategy_name = "moving_average_crossover"

    def __init__(
        self,
        fast_window: int = 20,
        slow_window: int = 50,
        price_col: str = "close",
        long_only: bool = True,
        **params: Any,
    ) -> None:
        super().__init__(fast_window=fast_window, slow_window=slow_window, price_col=price_col, long_only=long_only, **params)
        self.fast_window = int(fast_window)
        self.slow_window = int(slow_window)
        self.price_col = price_col
        self.long_only = bool(long_only)

    def on_bar(
        self,
        context: StrategyContext,
        historical_data: pd.DataFrame,
        features: pd.DataFrame | None = None,
    ) -> Mapping[str, float]:
        """Return the latest crossover signal for every ticker in context."""

        signals = self.generate_signals(context.metadata, historical_data, features)
        latest = signals[signals["date"] == pd.Timestamp(context.date)]
        return dict(zip(latest["ticker"], latest["signal"]))

    def generate_signals(
        self,
        current_state: Mapping[str, Any] | None,
        historical_data: pd.DataFrame,
        features: pd.DataFrame | None = None,
    ) -> pd.DataFrame:
        """Vectorized moving-average crossover signal generation."""

        if historical_data.empty:
            return pd.DataFrame(columns=["date", "ticker", "signal", "fast_ma", "slow_ma"])
        data = historical_data.copy()
        data["date"] = pd.to_datetime(data["date"], errors="coerce")
        if "ticker" not in data.columns:
            data["ticker"] = "ASSET"
        price_col = _resolve_price_col(data, self.price_col)
        if price_col is None:
            return pd.DataFrame(columns=["date", "ticker", "signal", "fast_ma", "slow_ma"])
        data = data.sort_values(["ticker", "date"])
        data["_price"] = pd.to_numeric(data[price_col], errors="coerce")
        grouped = data.groupby("ticker", group_keys=False)["_price"]
        data["fast_ma"] = grouped.transform(lambda s: s.rolling(self.fast_window, min_periods=max(1, self.fast_window // 2)).mean())
        data["slow_ma"] = grouped.transform(lambda s: s.rolling(self.slow_window, min_periods=max(1, self.slow_window // 2)).mean())
        short_value = 0.0 if self.long_only else -1.0
        data["signal"] = np.where(data["fast_ma"] > data["slow_ma"], 1.0, short_value)
        data.loc[data[["fast_ma", "slow_ma"]].isna().any(axis=1), "signal"] = 0.0
        return validate_signal_frame(data[["date", "ticker", "signal", "fast_ma", "slow_ma"]])


def validate_signal_frame(signals: pd.DataFrame) -> pd.DataFrame:
    """Return a normalized signal frame with required columns."""

    if signals is None or signals.empty:
        return pd.DataFrame(columns=["date", "ticker", "signal"])
    out = signals.copy()
    if "date" not in out.columns:
        raise ValueError("Signal frame must include a date column")
    if "ticker" not in out.columns:
        raise ValueError("Signal frame must include a ticker column")
    if "signal" not in out.columns and "target_weight" not in out.columns:
        raise ValueError("Signal frame must include either signal or target_weight")
    out["date"] = pd.to_datetime(out["date"], errors="coerce")
    out["ticker"] = out["ticker"].astype(str).str.upper()
    if "signal" in out.columns:
        out["signal"] = pd.to_numeric(out["signal"], errors="coerce").fillna(0.0)
    if "target_weight" in out.columns:
        out["target_weight"] = pd.to_numeric(out["target_weight"], errors="coerce").fillna(0.0)
    return out.dropna(subset=["date", "ticker"]).sort_values(["date", "ticker"]).reset_index(drop=True)


def _feature_slice(features: pd.DataFrame | None, date: pd.Timestamp) -> pd.DataFrame | None:
    if features is None or features.empty or "date" not in features.columns:
        return features
    dates = pd.to_datetime(features["date"], errors="coerce")
    return features[dates <= date]


def _coerce_bar_result(result: Mapping[str, float] | pd.DataFrame, date: pd.Timestamp) -> pd.DataFrame:
    if isinstance(result, pd.DataFrame):
        frame = result.copy()
        if "date" not in frame.columns:
            frame["date"] = date
        return frame
    return pd.DataFrame(
        [{"date": date, "ticker": ticker, "signal": value} for ticker, value in result.items()]
    )


def _resolve_price_col(data: pd.DataFrame, requested: str) -> str | None:
    for column in (requested, "adj_close", "close", "price", "mkt_price", "market_value"):
        if column in data.columns:
            return column
    return None

